version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - testapp
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 10s
      retries: 5

  testapp:
    image: testapp:latest
    restart: always
    environment:
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - STAGE=${STAGE}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - testapp
    links:
      - db

networks:
  testapp:
    driver: bridge
